var grammars = {
  poema: {
    origin: ["#oracionSencilla#"],

    oracionSencilla: [
      "#principio# #verboPasivo# #predicado# #adverbio#",
      "#principio# #verboActivo# #predicado# #adverbio#",
      "#principio# #verboPasivo# <br>#predicado.capitalize# #adverbio#",
      "#principio# #verboActivo# <br>#predicado.capitalize# #adverbio#",
      "#principio# #verboPasivo# #predicado#",
      "#principio# #verboActivo# #predicado#",
      "#principio# no #verboActivo# #predicado#",
      "#principio# no regresar #lugares#",
      "#principio# #verboPasivo# <br>Siento #sentimiento#",
      "#principio# #verboActivo# <br>Siento #sentimiento#",
      "#adverbioTiempoPasado.capitalize# tuve miedo de #verbos#",
      "#principio# no tener #sujetosPertenencia#",
    ],

    principio: [
      "Tengo miedo de",
      "A veces tengo miedo de",
      "Temo",
      "Me da miedo",
      "#adverbioTiempo.capitalize# tengo miedo de",
    ],

    sujetos: [
      "la noche",
      "el viento",
      "las paredes",
      "la risa",
      "tu recuerdo",
      "el sol",
      "la arena",
      "un autobús en la noche",
      "la ternura",
      "un abrazo",
      "tus manos",
      "el recuerdo",
      "el amanecer",
      "el examen",
      "el tiempo",
      "otro humano",
      "algo no humano",
      "un alienígena",
      "mi madre",
      "mi padre",
      "un cuento",
      "un asesinato",
      "un cuadro #adjetivo#",
    ],

    sujetosPertenencia: [
      "dinero",
      "una casa",
      "trabajo",
      "amor",
      "corazón",
      "vida",
      "coraje",
      "un carro",
      "una vida",
      "pareja",
      "felicidad",
      "cubiertos para todos",
      "invitados",
      "días soleados",
      "amor",
      "amistad verdadera",
      "cariño",
      "estabilidad económica",
      "un buen trabajo",
      "un trabajo que me guste",
      "sueños",
    ],

    lugares: [
      "a casa",
      "a la escuela",
      "al templo",
      "al parque",
      "al cine",
      "a la universidad",
      "a la facultad",
      "a la esquina",
      "a la tienda",
      "al bosque",
      "al mar",
      "a la playa",
    ],

    predicado: [
      "y no poder #verboConj1er#",
      "y sentirme #adjetivo#",
      "y #verboPasivo#",
      "y #verboActivo#",
      "y ver #sujetos#",
      "y me dio #sentimiento#",
      "#sujetos#",
    ],

    verboPasivo: [
      "despertar",
      "caminar",
      "ver",
      "escuchar",
      "presenciar",
      "fingir",
      "llorar",
      "cantar",
      "besar",
      "enfermar",
      "abrazar",
      "perder",
      "flotar",
      "percibir",
      "morir",
      "olvidar",
    ],
    verboActivo: [
      "gritar",
      "tomar",
      "engañar",
      "apretar",
      "golpear",
      "correr",
      "nadar",
      "bailar",
      "jugar",
      "cortar",
    ],

    verbos: ["#verboActivo#", "#verboActivo#"],

    adverbioLimitado: [
      "#adverbioLugar#",
      "#adverbioModo#",
      "#adverbioCantidad#",
    ],

    adjetivo: [
      "atrapado",
      "engañado",
      "solo",
      "triste",
      "preocupado",
      "mareado",
      "tonto",
      "vulnerable",
      "atraído",
      "amado",
      "desubicado",
      "hambriento",
      "viejo",
    ],
    verboConj1er: [
      "moverme",
      "reirme",
      "sentirme",
      "quererme",
      "hablarme",
      "gritarme",
      "odiarme",
      "olerme",
      "tocarme",
      "calmarme",
    ],

    sentimiento: [
      "dolor",
      "desesperación",
      "angustia",
      "cosquillas",
      "mareo",
      "náuseas ",
      "repulsión",
      "asco",
    ],

    adverbio: [
      "#adverbioLugar#",
      "#adverbioTiempo#",
      "#adverbioModo#",
      "#adverbioCantidad#",
      "#adverbioNAD#",
      "",
    ],

    adverbioLugar: [
      "aquí",
      "allá",
      "arriba",
      "cerca",
      "debajo",
      "fuera",
      "adelante",
      "allí",
      "acá",
      "delante",
      "detrás",
      "atrás",
      "enfrente",
      "afuera",
      "ahí",
      "abajo",
      "lejos",
      "encima",
      "dentro",
      "alrededor",
    ],

    adverbioTiempo: [
      "hoy",

      "siempre",
      "aún",
      "todavía",
      "temprano",
      "pronto",
      "mañana",
      "luego",
      "ahora",

      "nunca",
      "después",
      "mientras",
      "jamás",
    ],

    adverbioTiempoPasado: [
      "antes",
      "siempre",
      "aún",
      "temprano",
      "ahora",
      "anoche",
      "ayer",
      "nunca",
      "después",
      "mientras",
      "jamás",
    ],

    adverbioModo: [
      "así",
      "bien",
      "como",
      "alto",
      "claro",
      "rápido",
      "mejor",
      "mal",
      "adrede",
      "despacio",
      "fuerte",
      "lento",
      "según",
      "peor",
      "igual",
      "bajo",
      "deprisa",
      "regular",
      "raro",
    ],

    adverbioCantidad: [
      "nada",
      "mucho",
      "casi",
      "bastante",
      "medio",
      "totalmente",
      "todo",
      "poco",
      "más",
      "apenas",
      "algo",
      "demasiado",
      "bien",
      "menos",
      "tanto",
    ],

    adverbioNAD: [
      "sí",
      "exacto",
      "también",
      "no",
      "jamás",
      "quizás",
      "igual",
      "seguro",
      "nunca",
      "claro",
      "tampoco",
      "siquiera",
      "acaso",
    ],
  },
};
